global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Atlas2 API
  - job_name: 'atlas2-api'
    static_configs:
      - targets: ['atlas2-api:3001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Atlas2 Web (Nginx)
  - job_name: 'atlas2-web'
    static_configs:
      - targets: ['atlas2-web:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # PostgreSQL (if postgres_exporter is added)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Redis (if redis_exporter is added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s